# Generated by Django 3.0.3 on 2021-07-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('playlist', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('company_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('session_duration', models.CharField(max_length=50)),
            ],
        ),
    ]
