# Generated by Django 3.0.3 on 2021-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
